---
title: "analysis"
author: "Hasley Deniel Walker 23031585"
date: "2023-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(patchwork)
df <- read.csv("data007.csv")
df = df[-1]

x<- df$x
y <- df$y
z <- df$z

print(x[1:5])
```

```{r}
p1= ggplot(data=df,aes(x=Time,y=x)) + geom_line()
p2 = ggplot(data=df,aes(x=Time,y=y)) + geom_line()
p3 = ggplot(data=df,aes(x=Time,y=z)) + geom_line()

print(p1/p2/p3)


```
```{r}
#fourier transform
acq.freq <- 25                   # data acquisition frequency (Hz)
time     <-               # measuring time interval (seconds)
ts       <- seq(0,time,1/acq.freq) # vector of sampling time-points (s) 
f.0      <- 1/time                 # fundamental frequency (Hz)

dc.component       <- 0
component.freqs    <- c(3,10)      # frequency of signal components (Hz)
component.delay    <- c(0,0)       # delay of signal components (radians)
component.strength <- c(.5,.25)    # strength of signal components

f <- function(t,w) { 
  dc.component + 
  sum( component.strength * sin(component.freqs*w*t + component.delay)) 
}

plot.fourier <- function(fourier.series, f.0, ts) {
  w <- 2*pi*f.0
  trajectory <- sapply(ts, function(t) fourier.series(t,w))
  plot(ts, trajectory, type="l", xlab="time", ylab="f(t)"); abline(h=0,lty=3)
}

```

source: http://www.di.fc.ul.pt/~jpn/r/fourier/fourier.html

```{r}
plot.frequency.spectrum <- function(X.k, xlimits=c(0,length(X.k))) {
  plot.data  <- cbind(0:(length(X.k)-1), Mod(X.k))

  # TODO: why this scaling is necessary?
  plot.data[2:length(X.k),2] <- 2*plot.data[2:length(X.k),2] 
  
  plot(plot.data, t="h", lwd=2, main="", 
       xlab="Frequency (Hz)", ylab="Strength", 
       xlim=xlimits, ylim=c(0,max(Mod(plot.data[,2]))))
}

X.k <- fft(x)
acq.freq <- 25
plot.frequency.spectrum(X.k,xlimits=c(0,acq.freq/2))
```


```{r}
attach(df)
df$accelation_magnitude <- sqrt(df$x^2+df$y^2+df$z^2)
head(df)

df.summ <- summary(df$accelation_magnitude)
cat("median:",median(df$accelation_magnitude))
cat("\nsd:",sd(df$accelation_magnitude))

```
time analysis
```{r}
attach(df)

delta_x <- c()
delta_y <- c()
delta_z <- c()

for(i in 1:(length(x)-1)){
  delta_x <- append(delta_x, x[i+1] - x[i])
  delta_y <- append(delta_y, y[i+1] - y[i])
  delta_z <- append(delta_z, z[i+1] - z[i])
}


```

